-- AlterTable
ALTER TABLE `solicitacao` MODIFY `status` ENUM('AGUARDANDO_APROVACAO', 'AGUARDANDO_COLETA', 'FINALIZAR_PAGAMENTO', 'AGUARDANDO_PAGAMENTO', 'FINALIZADO', 'CANCELADO') NOT NULL DEFAULT 'AGUARDANDO_APROVACAO';
