-- AlterTable
ALTER TABLE `Solicitacao` MODIFY `status` ENUM('AGUARDANDO_APROVACAO', 'AGUARDANDO_COLETA', 'FINALIZAR_PAGAMENTO', 'AGUARDANDO_PAGAMENTO', 'LAUDO_VALIDADO', 'AGUARDANDO_LAUDO', 'FINALIZADO', 'CANCELADO') NOT NULL DEFAULT 'AGUARDANDO_APROVACAO';
